<!DOCTYPE html>
<html>
<head>
    <title>PROMISE</title>
</head>
<body>
    <script>
        // Exercici 1
        function divisible(numero){
            return new Promise((resolve, reject) => {
                if (numero % 2 === 0){
                    resolve(`${numero} Es divisible entre 2`)
                } else {
                    reject(`${numero} No es divisible entre 2`)
                }
            });
        }
        // Exercici 2
        function comprobaRango(valor){
            return new Promise((resolve, reject) => {
                if (valor >= 0 && valor <= 10){
                    resolve(`${valor} esta a dins del rang del 0 al 10`)
                } else {
                    reject(`${valor} esta a fora del rang del 0 al 10`)
                }
            });
        } 
        // Exercici 3
        function lletres(vocal) {
            const arrayVocals = ["a","e","i","o","u"];
            return new Promise((resolve, reject) => {
                if (arrayVocals.includes(vocal)){
                    resolve(`${vocal} es una vocal`)
                } else {
                    reject(`${vocal} no es una vocal`)
                }
            });
        }
        // Exercici 4
        function divisio(a,b){
            return new Promise((resolve, reject) => {
                if (b === 0){
                    reject("No es pot dividir entre 0");
                } else {
                    resolve(a/b);
                }
            });
        }
        // RESULTATS
        divisible(10)
            .then(divisio => console.log(divisio))
            .catch(noDivisio => console.log(noDivisio));

        comprobaRango(5)
            .then(dinsRango => console.log(dinsRango))
            .catch(noDinsRango => console.log(noDinsRango));

        lletres("a")
            .then(esVocal => console.log(esVocal))
            .catch(noVocal => console.log(noVocal));

        divisio(10,15)
            .then(DivisioSi => console.log("Resultat dela divisio: ", DivisioSi))
            .catch(DivisioError => console.error("Error en la divisio: ", DivisioError));     
    </script>
</body>
</html>
